# -*- coding: utf-8 -*-
"""beta waves_extraction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZGShDhS6fbyoqF2MCA2u2hPvt0OOwX9k
"""

from google.colab import drive
drive.mount('drive')
!pip install mne;

import os
import numpy as np
import mne
import pandas as pd
import matplotlib.pyplot as plt 
from pathlib import Path
import pywt

image_dir =Path('/content/drive/MyDrive/eval')
filepaths=pd.Series(list(image_dir.glob(r'*.csv')),name='Filepath')
filepaths

data = np.loadtxt('/content/drive/MyDrive/eval/00000647_s002_t000.csv', delimiter=',')

data[:,0:30].shape

j=1

for i in filepaths[0:126]:
  data = np.loadtxt(i, delimiter=',')
  df=pd.DataFrame(data=data[:,0:27])
  ch_names = ['CH 1', 'CH 2', 'CH 3','CH4','CH5','CH6','CH7','CH8','CH9','CH10','CH11','CH12','CH13','CH14','CH15','CH16','CH17','CH18','CH19','CH20','CH21','CH22','CH23','CH24','CH25','CH26','CH27'] 
  df.columns=ch_names
  sfreq = 250 
  info = mne.create_info(ch_names, sfreq)
  raw = mne.io.RawArray(data[:,0:27].transpose(), info)
  raw.filter(1,64,picks=['CH 1', 'CH 2', 'CH 3','CH4','CH5','CH6','CH7','CH8','CH9','CH10','CH11','CH12','CH13','CH14','CH15','CH16','CH17','CH18','CH19','CH20','CH21','CH22','CH23','CH24','CH25','CH26','CH27'])
  X=pd.DataFrame(raw.get_data().transpose())
  coeffs = pywt.wavedec(X[0], 'db8', level=5,mode='ppd')
  cA4,cD5,cD4,cD3,cD2,cD1 = coeffs
  beta=pd.DataFrame(cD3,columns=[0])
  
  for i in range(1,len(X.columns)):
    
    coeffs = pywt.wavedec(X[i], 'db8', level=5,mode='ppd')
    cA4,cD5,cD4,cD3,cD2,cD1 = coeffs                         
    beta[i]=cD3
  beta.to_csv('/content/drive/MyDrive/BETA'+'/'+'beta_'+str(j)+'.csv')
  j=j+1

j=1

for i in filepaths[0:126]:
  data = np.loadtxt(i, delimiter=',')
  df=pd.DataFrame(data=data[:,0:30])
  ch_names = ['CH 1', 'CH 2', 'CH 3','CH4','CH5','CH6','CH7','CH8','CH9','CH10','CH11','CH12','CH13','CH14','CH15','CH16','CH17','CH18','CH19','CH20','CH21','CH22','CH23','CH24','CH25','CH26','CH27','CH28','CH29','CH30'] 
  df.columns=ch_names
  sfreq = 250 
  info = mne.create_info(ch_names, sfreq)
  raw = mne.io.RawArray(data[:,0:30].transpose(), info)
  b=raw.filter(1,64,picks=['CH 1', 'CH 2', 'CH 3','CH4','CH5','CH6','CH7','CH8','CH9','CH10','CH11','CH12','CH13','CH14','CH15','CH16','CH17','CH18','CH19','CH20','CH21','CH22','CH23','CH24','CH25','CH26','CH27','CH28','CH29','CH30'])
  X=pd.DataFrame(b.get_data().transpose())
  coeffs = pywt.wavedec(X[0], 'db8', level=5,mode='ppd')
  cA4,cD5,cD4,cD3,cD2,cD1 = coeffs
  alpha=pd.DataFrame(cD4,columns=[0])
  
  for i in range(1,len(X.columns)):
    
    coeffs = pywt.wavedec(X[i], 'db8', level=5,mode='ppd')
    cA4,cD5,cD4,cD3,cD2,cD1 = coeffs                         
    alpha[i]=cD4
  alpha.to_csv('/content/drive/MyDrive/HW11'+'/'+'alpha_'+str(j)+'.csv')
  j=j+1

j=1

for i in filepaths[0:1]:
  data = np.loadtxt(i, delimiter=',')
  df=pd.DataFrame(data=data)
  ch_names = ['CH 1', 'CH 2', 'CH 3','CH4','CH5','CH6','CH7','CH8','CH9','CH10','CH11','CH12','CH13','CH14','CH15','CH16','CH17','CH18','CH19','CH20','CH21','CH22','CH23','CH24','CH25','CH26','CH27','CH28','CH29','CH30','CH31','CH32','CH33','CH34','CH35','CH36'] 
  df.columns=ch_names
  sfreq = 250 
  info = mne.create_info(ch_names, sfreq)
  raw = mne.io.RawArray(data.transpose(), info)
  b=raw.filter(1,64,picks=['CH 1', 'CH 2', 'CH 3','CH4','CH5','CH6','CH7','CH8','CH9','CH10','CH11','CH12','CH13','CH14','CH15','CH16','CH17','CH18','CH19','CH20','CH21','CH22','CH23','CH24','CH25','CH26','CH27','CH28','CH29','CH30','CH31','CH32','CH33','CH34','CH35','CH36'] )
  X=pd.DataFrame(b.get_data().transpose())
  coeffs = pywt.wavedec(X[0], 'db8', level=8,mode='ppd')
  cA4,cD8,cD7,cD6,cD5,cD4,cD3,cD2,cD1 = coeffs
  alpha=pd.DataFrame(cD8,columns=[0])
  
  for i in range(1,len(X.columns)):
    
    coeffs = pywt.wavedec(X[i], 'db8', level=8,mode='ppd')
    cA4,cD8,cD7,cD6,cD5,cD4,cD3,cD2,cD1 = coeffs
    alpha[i]=cD8
  alpha.to_csv('/content/drive/MyDrive/HW11'+'/'+'alpha_'+str(j)+'.csv')
  j=j+1

j=95

for i in filepaths[95:126]:
  data = np.loadtxt(i, delimiter=',')
  df=pd.DataFrame(data=data[:,0:27])
  ch_names = ['CH 1', 'CH 2', 'CH 3','CH4','CH5','CH6','CH7','CH8','CH9','CH10','CH11','CH12','CH13','CH14','CH15','CH16','CH17','CH18','CH19','CH20','CH21','CH22','CH23','CH24','CH25','CH26','CH27'] 
  df.columns=ch_names
  sfreq = 250 
  info = mne.create_info(ch_names, sfreq)
  raw = mne.io.RawArray(data[:,0:27].transpose(), info)
  b=raw.filter(1,64,picks=['CH 1', 'CH 2', 'CH 3','CH4','CH5','CH6','CH7','CH8','CH9','CH10','CH11','CH12','CH13','CH14','CH15','CH16','CH17','CH18','CH19','CH20','CH21','CH22','CH23','CH24','CH25','CH26','CH27'])
  X=pd.DataFrame(b.get_data().transpose())
  coeffs = pywt.wavedec(X[0], 'db8', level=5,mode='ppd')
  cA4,cD5,cD4,cD3,cD2,cD1 = coeffs
  alpha=pd.DataFrame(cD4,columns=[0])
  
  for i in range(1,len(X.columns)):
    
    coeffs = pywt.wavedec(X[i], 'db8', level=5,mode='ppd')
    cA4,cD5,cD4,cD3,cD2,cD1 = coeffs
    alpha[i]=cD4
  alpha.to_csv('/content/drive/MyDrive/HW11'+'/'+'alpha_'+str(j)+'.csv')
  j=j+1

X=pd.read_csv('/content/drive/MyDrive/HW11/alpha_1.csv',index_col=0)
X

pd.read_csv('/content/drive/MyDrive/HW11/alpha_2.csv')

ch_names = ['CH 1', 'CH 2', 'CH 3','CH4','CH5','CH6','CH7','CH8','CH9','CH10','CH11','CH12','CH13','CH14','CH15','CH16','CH17','CH18','CH19','CH20','CH21','CH22','CH23','CH24','CH25','CH26','CH27','CH28','CH29','CH30','CH31','CH32','CH33','CH34','CH35','CH36']  # TODO: finish this list

# Sampling rate of the Nautilus machine
sfreq = 250 

# Create the info structure needed by MNE
info = mne.create_info(ch_names, sfreq)
raw = mne.io.RawArray(X.transpose(), info)

raw.plot_psd(picks=['CH 1', 'CH 2', 'CH 3'])

